image: python:3.7

before_script:
  - python3 -m venv env
  - source env/bin/activate
  - pip3 install -r requirements.txt

lint:
  script:
    - flake8 --ignore=E501,F,W lib/*.py main.py

run_test:
  script:
    - pytest -v lib/test.py
